repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-ast
          - id: check-builtin-literals
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: check-yaml
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
            args: [-S, -l 120]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-blind-except==0.1.1
                - flake8-bugbear==20.1.4
                - flake8-builtins==1.5.3
                - flake8-comprehensions==3.3.0
                - flake8-eradicate==1.0.0
                - flake8-import-order==0.18.1
    - repo: https://github.com/PyCQA/pydocstyle
      rev: 5.1.1
      hooks:
          - id: pydocstyle
            args: [--convention=numpy, "--add-ignore=D104,D105"]
            exclude: skspatial/tests|examples|conf.py
