version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - method: setuptools
      path: .
    - method: pip
      path: .
      extra_requirements:
        - requirements/docs.txt
